### ISSUE TITLE
print/logging issue on iOS

### ISSUE THREAD

**Issue by derrickshowers** [denisPoifol/CombinePlaygrounds#2]
Printing does not work inside completion blocks on iOS. Have you seen this before? See attached video. I was running into this on a project I’m working on and thought it was something I did. But also happening with this playground book.

![E8437094-65CA-4B42-87CF-DE1539286AB3](https://user-images.githubusercontent.com/1372292/80820131-4ebb0c00-8ba4-11ea-9df0-70e397e7527e.gif)

_Also... thanks for putting this together! I’m actually working on a similar thing and hope to publish it by the end of this month, although I’m way further behind than you. I love the idea of using playground books to learn and then teach others._

**Comment by denisPoifol** [comment]
I am not sure I fully understand what your issue is.
But print statement do work inside of completion blocks, they are only executed once the completion block is executed itself.

But they will appear in the debugging console not on quick display of the playground.

<img width="1351" alt="Screenshot 2020-05-02 at 21 16 35" src="https://user-images.githubusercontent.com/12525029/80873616-39380600-8cba-11ea-9975-1abe8157dbb1.png">

Does this answer your question?

**Comment by derrickshowers** [comment]
Ah, this is Xcode, right? Playgrounds on iOS doesn’t have a console (yet) so there’s no way to see the output. What’s odd though is they will show in quick display if you have another print statement above line 17. 

Seems like a Playgrounds iOS bug...

**Comment by denisPoifol** [comment]
Ok I get it know, for a second I completely forgot about the iOS application. 
🤔I'll see what I can do to make it usable on the application, though I am not familiar with it.

**Comment by derrickshowers** [comment]
Nah I’m just glad it’s not just me. Let me know if you come up with anything. There’s also a macOS version (uses catalyst so works the same). I’ll look into how to report this (not sure if it follows the typical radar process).

Anyhow, well done overall! Learned a lot reading through it!

**Comment by denisPoifol** [comment]
@derrickshowers It should be usable now.
I created a Logger class that returns the strings value so it can be seen in the swift playground application. (This is only true for the master branch but I will also fix it on the CombineInDepthBranch)
Unfortunately for pages like TimeOperator, the inability of swift playground to run only part of the code still makes it hard to fully gain from the experience but for the rest it should be a big improvement.
Let me know if you see something buggy.

**Comment by derrickshowers** [comment]
This is a smart solution, thanks for adding!
